// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoliticalAlertsWeb.Models;

namespace PoliticalAlertsWeb.Migrations
{
    [DbContext(typeof(AlertsDbContext))]
    [Migration("20220417185544_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PoliticalAlerts.Models.AgendaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Retrieved")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("AgendaItems");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AgendaItemId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgendaItemId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AgendaItemId")
                        .HasColumnType("int");

                    b.Property<string>("Excerpt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MeetingId")
                        .HasColumnType("int");

                    b.Property<int?>("SearchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeFound")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeNotified")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AgendaItemId");

                    b.HasIndex("MeetingId");

                    b.HasIndex("SearchId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BoardId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoardName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.Observer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Emails")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<string>("SmtpSender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpServer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SmtpUseSsl")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Observers");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.ObserverSearch", b =>
                {
                    b.Property<int>("ObserverId")
                        .HasColumnType("int");

                    b.Property<int>("SearchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Activated")
                        .HasColumnType("datetime2");

                    b.HasKey("ObserverId", "SearchId");

                    b.HasIndex("SearchId");

                    b.ToTable("ObserverSearches");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.Search", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phrase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Searches");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.SearchSource", b =>
                {
                    b.Property<int>("SearchId")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.HasKey("SearchId", "SourceId");

                    b.HasIndex("SourceId");

                    b.ToTable("SearchSources");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.SeenAgendaItem", b =>
                {
                    b.Property<int>("SearchId")
                        .HasColumnType("int");

                    b.Property<int>("AgendaItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateSeen")
                        .HasColumnType("datetime2");

                    b.HasKey("SearchId", "AgendaItemId");

                    b.HasIndex("AgendaItemId");

                    b.ToTable("SeenAgendaItems");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.StorageConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ObserverId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ObserverId");

                    b.ToTable("StorageConfig");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.TaskManagerConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ObserverId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ObserverId");

                    b.ToTable("TaskManagerConfig");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.AgendaItem", b =>
                {
                    b.HasOne("PoliticalAlerts.Models.Meeting", "Meeting")
                        .WithMany("AgendaItems")
                        .HasForeignKey("MeetingId");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.Document", b =>
                {
                    b.HasOne("PoliticalAlerts.Models.AgendaItem", "AgendaItem")
                        .WithMany("Documents")
                        .HasForeignKey("AgendaItemId");

                    b.Navigation("AgendaItem");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.Match", b =>
                {
                    b.HasOne("PoliticalAlerts.Models.AgendaItem", "AgendaItem")
                        .WithMany("Matches")
                        .HasForeignKey("AgendaItemId");

                    b.HasOne("PoliticalAlerts.Models.Meeting", null)
                        .WithMany("Matches")
                        .HasForeignKey("MeetingId");

                    b.HasOne("PoliticalAlerts.Models.Search", "Search")
                        .WithMany("Matches")
                        .HasForeignKey("SearchId");

                    b.Navigation("AgendaItem");

                    b.Navigation("Search");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.Meeting", b =>
                {
                    b.HasOne("PoliticalAlerts.Models.Source", "Source")
                        .WithMany("Meetings")
                        .HasForeignKey("SourceId");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.ObserverSearch", b =>
                {
                    b.HasOne("PoliticalAlerts.Models.Observer", "Observer")
                        .WithMany("SubscribedSearches")
                        .HasForeignKey("ObserverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalAlerts.Models.Search", "Search")
                        .WithMany("Subscribers")
                        .HasForeignKey("SearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observer");

                    b.Navigation("Search");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.Search", b =>
                {
                    b.HasOne("PoliticalAlerts.Models.Observer", "CreatedBy")
                        .WithMany("CreatedSearches")
                        .HasForeignKey("CreatedById");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.SearchSource", b =>
                {
                    b.HasOne("PoliticalAlerts.Models.Search", "Search")
                        .WithMany("Sources")
                        .HasForeignKey("SearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalAlerts.Models.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Search");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.SeenAgendaItem", b =>
                {
                    b.HasOne("PoliticalAlerts.Models.AgendaItem", "AgendaItem")
                        .WithMany()
                        .HasForeignKey("AgendaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalAlerts.Models.Search", "Search")
                        .WithMany("SeenAgendaItems")
                        .HasForeignKey("SearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgendaItem");

                    b.Navigation("Search");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.StorageConfig", b =>
                {
                    b.HasOne("PoliticalAlerts.Models.Observer", null)
                        .WithMany("Storage")
                        .HasForeignKey("ObserverId");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.TaskManagerConfig", b =>
                {
                    b.HasOne("PoliticalAlerts.Models.Observer", null)
                        .WithMany("TaskManager")
                        .HasForeignKey("ObserverId");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.AgendaItem", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.Meeting", b =>
                {
                    b.Navigation("AgendaItems");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.Observer", b =>
                {
                    b.Navigation("CreatedSearches");

                    b.Navigation("Storage");

                    b.Navigation("SubscribedSearches");

                    b.Navigation("TaskManager");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.Search", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("SeenAgendaItems");

                    b.Navigation("Sources");

                    b.Navigation("Subscribers");
                });

            modelBuilder.Entity("PoliticalAlerts.Models.Source", b =>
                {
                    b.Navigation("Meetings");
                });
#pragma warning restore 612, 618
        }
    }
}
